"""
DEMO_MODE: run the audit workflow end to end without LLM keys or AWS access.

When ``DEMO_MODE=1`` the flow swaps each phase crew for a :class:`DemoCrew`
that returns fixed, schema-valid artifacts and an approving QA result. Only
the crew is replaced: the AuditFlow state machine, QA-gate bookkeeping,
human gates, approval trail and API stream events are the real ones.

Every demo artifact says it is demo data. Nothing in it was collected from
an AWS account or written by a model, and it makes no compliance claim.

DEMO_MODE is refused in ``ENVIRONMENT=production`` / ``staging`` (see
:func:`demo_mode_enabled`); the API checks this at startup.

``DEMO_QA_REJECT_PHASE=n`` (1-3) makes the demo QA reviewer reject phase *n*
until a human retries it, so the retry and QA-override paths can be demoed.
"""

from __future__ import annotations

import json
import logging
import os
import time
from types import SimpleNamespace
from typing import Any, Callable, Optional

from swarm.evidence import EvidenceAssuranceProtocol
from swarm.schema import (
    AuditFindingSchema,
    Control,
    ControlTestStep,
    ControlTesting,
    FinalReportSchema,
    OSCAL_SAR_ImportAP,
    OSCAL_SAR_Metadata,
    OSCAL_SAR_Observation,
    OSCAL_SAR_Result,
    OSCAL_SAR_Schema,
    QA_PushbackSchema,
    Risk,
    RiskControlMatrixSchema,
    WorkingPaperSchema,
)

logger = logging.getLogger(__name__)

DEMO_LABEL = "DEMO DATA"
DEMO_NOTICE = (
    "DEMO DATA — generated by DEMO_MODE from fixed sample content. No language "
    "model was called and no AWS account was examined; the evidence referenced "
    "is synthetic; it is stored in the evidence vault under a DEMO DATA label "
    "so quote verification can be shown working. Not an audit opinion."
)

_TRUTHY = {"1", "true", "yes", "on"}
_BLOCKED_ENVIRONMENTS = {"production", "prod", "staging", "stage"}


class DemoModeNotAllowedError(RuntimeError):
    """DEMO_MODE was requested in an environment where it is refused."""


def demo_mode_requested() -> bool:
    return os.environ.get("DEMO_MODE", "0").strip().lower() in _TRUTHY


def demo_mode_enabled() -> bool:
    """True when DEMO_MODE is on; raises if it is on in production/staging."""
    if not demo_mode_requested():
        return False
    environment = os.environ.get("ENVIRONMENT", "local").strip().lower()
    if environment in _BLOCKED_ENVIRONMENTS:
        raise DemoModeNotAllowedError(
            f"DEMO_MODE=1 is not allowed when ENVIRONMENT={environment!r}: demo "
            "mode replaces the audit crews with fixed sample artifacts. Unset "
            "DEMO_MODE (or set it to 0) for this deployment."
        )
    return True


def demo_reject_phase() -> Optional[int]:
    raw = os.environ.get("DEMO_QA_REJECT_PHASE", "").strip()
    return int(raw) if raw in {"1", "2", "3"} else None


def _step_delay() -> float:
    try:
        return min(max(float(os.environ.get("DEMO_STEP_DELAY", "0.4")), 0.0), 5.0)
    except ValueError:
        return 0.4


# ── Fixed artifacts ──────────────────────────────────────────────────────────


def _step(description: str, expected: str) -> ControlTestStep:
    return ControlTestStep(step_description=description, expected_result=expected)


def demo_racm(theme: str = "") -> RiskControlMatrixSchema:
    return RiskControlMatrixSchema(
        theme=f"[{DEMO_LABEL}] {theme or 'AWS Cloud Security'}",
        risks=[
            Risk(
                risk_id="RISK-01",
                description=(
                    f"[{DEMO_LABEL}] Unauthorized access to IAM or S3 resources."
                ),
                regulatory_mapping=["CIS AWS Foundations (demo mapping)"],
                controls=[
                    Control(
                        control_id="CTRL-01",
                        description="Enforce a strict IAM password policy.",
                        testing_procedures=ControlTesting(
                            test_of_design=[
                                _step(
                                    "Verify that a password policy is defined in IAM.",
                                    "Password policy exists and is configured.",
                                )
                            ],
                            test_of_effectiveness=[
                                _step(
                                    "Run the get_iam_password_policy tool.",
                                    "Minimum length and complexity match the "
                                    "organisation's standard.",
                                )
                            ],
                            substantive_testing=[
                                _step(
                                    "Compare the policy values with the benchmark.",
                                    "Each value meets or exceeds the benchmark.",
                                )
                            ],
                        ),
                    ),
                    Control(
                        control_id="CTRL-02",
                        description="Block public access on S3 buckets.",
                        testing_procedures=ControlTesting(
                            test_of_design=[
                                _step(
                                    "Confirm account-level S3 Block Public Access "
                                    "is configured.",
                                    "All four Block Public Access settings are on.",
                                )
                            ],
                            test_of_effectiveness=[
                                _step(
                                    "List buckets and inspect each bucket's "
                                    "public access block.",
                                    "No bucket allows public ACLs or policies.",
                                )
                            ],
                            substantive_testing=None,
                        ),
                    ),
                ],
            )
        ],
    )


def _controls_from_racm_json(racm_json: str) -> list[str]:
    try:
        racm = RiskControlMatrixSchema.model_validate_json(racm_json)
    except Exception:
        racm = demo_racm()
    return [c.control_id for r in racm.risks for c in r.controls]


_DEMO_FINDINGS = [
    (
        "Pass",
        "PasswordPolicy: MinimumPasswordLength=14",
        "The sample password policy meets the length requirement in the test step.",
    ),
    (
        "Control Deficiency",
        "BlockPublicAcls: false",
        "One sample bucket does not block public ACLs; remediation would be needed.",
    ),
]


def _register_demo_evidence(control_id: str, quote: str) -> str:
    """Store a synthetic evidence record in the vault and return its vault ID.

    The payload is labelled as demo data and contains the quote verbatim, so
    the vault's hashing and quote verification run for real on it.
    """
    payload = json.dumps(
        {
            "label": f"{DEMO_LABEL} - synthetic evidence, not collected from "
            "any AWS account",
            "control_id": control_id,
            "evidence": quote,
        },
        indent=2,
    )
    record = EvidenceAssuranceProtocol.register_evidence(
        payload, "demo_mode_synthetic_evidence"
    )
    return record["vault_id"]


def demo_working_papers(theme: str = "", racm_json: str = "") -> WorkingPaperSchema:
    controls = _controls_from_racm_json(racm_json) if racm_json else ["CTRL-01"]
    findings = []
    for i, control_id in enumerate(controls):
        severity, quote, conclusion = _DEMO_FINDINGS[i % len(_DEMO_FINDINGS)]
        findings.append(
            AuditFindingSchema(
                control_id=control_id,
                vault_id_reference=_register_demo_evidence(control_id, quote),
                exact_quote_from_evidence=quote,
                test_conclusion=f"[{DEMO_LABEL} — synthetic evidence] {conclusion}",
                severity=severity,
            )
        )
    return WorkingPaperSchema(
        theme=f"[{DEMO_LABEL}] {theme or 'AWS Cloud Security'}", findings=findings
    )


def demo_final_report(theme: str = "", papers_json: str = "") -> FinalReportSchema:
    try:
        papers = WorkingPaperSchema.model_validate_json(papers_json)
    except Exception:
        papers = demo_working_papers(theme)
    counts: dict[str, int] = {}
    for f in papers.findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    tally = ", ".join(f"{n} × {sev}" for sev, n in sorted(counts.items())) or "none"
    lines = [
        f"- {f.control_id} ({f.severity}): {f.test_conclusion} "
        f"[evidence ref {f.vault_id_reference}]"
        for f in papers.findings
    ]
    now = "2026-01-01T00:00:00+00:00"  # fixed: demo output is deterministic
    return FinalReportSchema(
        executive_summary=(
            f"{DEMO_NOTICE}\n\nThe demo walk-through evaluated "
            f"{len(papers.findings)} sample control(s): {tally}."
        ),
        detailed_report=(f"{DEMO_NOTICE}\n\nSample findings:\n" + "\n".join(lines)),
        compliance_tone_approved=True,
        oscal_sar=OSCAL_SAR_Schema(
            metadata=OSCAL_SAR_Metadata(
                title=f"[{DEMO_LABEL}] {theme or 'Demo audit'} — sample results",
                last_modified=now,
                version="demo",
            ),
            import_ap=OSCAL_SAR_ImportAP(
                href="demo://assessment-plan",
                remarks="Demo data: no assessment plan exists.",
            ),
            results=[
                OSCAL_SAR_Result(
                    assessment_result_id="demo-result-1",
                    start_date=now,
                    end_date=now,
                    observations=[
                        OSCAL_SAR_Observation(
                            observation_id=f"demo-obs-{i + 1}",
                            description=f"[{DEMO_LABEL}] {f.test_conclusion}",
                            methods=["test"],
                            subjects=[f.control_id],
                            relevant_evidence=[f.vault_id_reference],
                        )
                        for i, f in enumerate(papers.findings)
                    ],
                )
            ],
        ),
    )


# ── Demo crew ────────────────────────────────────────────────────────────────

# (task name, agent role as in the crew YAML configs)
_PHASE_TASKS: dict[int, list[tuple[str, str]]] = {
    1: [
        ("context_task", "Audit Director"),
        ("crosswalk_task", "Regulatory & Threat Analyst"),
        ("weighting_task", "Risk & Threat Specialist"),
        ("racm_drafting_task", "Senior IT Auditor"),
        ("qa_gate_task", "Quality & Pushback Reviewer"),
    ],
    2: [
        ("evidence_collection_task", "Field Evidence Collector"),
        ("execution_evaluation_task", "IT Field Auditor"),
        ("eval_qa_gate_task", "Execution QA & Pushback Reviewer"),
    ],
    3: [
        ("drafting_task", "Lead Report Writer"),
        ("executive_summary_task", "Chief Audit Executive (CAE)"),
        ("tone_qa_task", "Reporting Tone & QA Reviewer"),
        ("generate_oscal_sar_task", "Compliance Documentation Engineer"),
        ("final_report_assembly_task", "Lead Report Writer"),
    ],
}
_QA_TASK = {1: "qa_gate_task", 2: "eval_qa_gate_task", 3: "tone_qa_task"}
_ARTIFACT_TASK = {
    1: "racm_drafting_task",
    2: "execution_evaluation_task",
    3: "final_report_assembly_task",
}


class DemoCrew:
    """Stands in for a phase crew: same ``kickoff(inputs=…)`` contract and
    task names, fixed outputs, and step events through ``event_callback``."""

    def __init__(
        self,
        phase: int,
        event_callback: Optional[Callable[[Any], None]] = None,
        *,
        reject: bool = False,
    ) -> None:
        if phase not in _PHASE_TASKS:
            raise ValueError("phase must be 1, 2, or 3")
        self.phase = phase
        self._event_callback = event_callback
        self._reject = reject

    def _artifact(self, inputs: dict[str, Any]) -> Any:
        theme = str(inputs.get("theme", ""))
        if self.phase == 1:
            return demo_racm(theme)
        if self.phase == 2:
            return demo_working_papers(theme, str(inputs.get("racm_string", "")))
        return demo_final_report(theme, str(inputs.get("working_papers_string", "")))

    def _qa(self) -> QA_PushbackSchema:
        if self._reject:
            return QA_PushbackSchema(
                approved=False,
                rejection_reason=(
                    f"[{DEMO_LABEL}] Simulated QA rejection "
                    f"(DEMO_QA_REJECT_PHASE={self.phase}) so the retry and "
                    "override actions can be demonstrated."
                ),
            )
        return QA_PushbackSchema(approved=True, rejection_reason=None)

    def kickoff(self, inputs: dict[str, Any]) -> Any:
        artifact = self._artifact(inputs)
        qa = self._qa()
        delay = _step_delay()
        outputs = []
        for task_name, role in _PHASE_TASKS[self.phase]:
            if task_name == _QA_TASK[self.phase]:
                pydantic: Any = qa
            elif task_name == _ARTIFACT_TASK[self.phase]:
                pydantic = artifact
            else:
                pydantic = None
            if delay:
                time.sleep(delay)
            if self._event_callback is not None:
                preview = (
                    json.dumps(pydantic.model_dump(), default=str)[:200]
                    if pydantic is not None
                    else f"[{DEMO_LABEL}] {task_name} completed (no model call)."
                )
                self._event_callback(SimpleNamespace(agent=role, output=preview))
            outputs.append(SimpleNamespace(name=task_name, pydantic=pydantic))
        logger.info("DEMO_MODE: phase %d crew replaced with demo output", self.phase)
        return SimpleNamespace(tasks_output=outputs)
