from datetime import UTC, datetime
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field, field_validator

from swarm.evidence import ControlEvidence
from swarm.workflow_types import ExecutionStatus


# --- Traceability & Audit Logging ---
class AuditAction(BaseModel):
    timestamp: str = Field(default_factory=lambda: datetime.now(UTC).isoformat())
    agent_or_user_id: str = Field(
        description="Who performed the action (e.g., 'ScopeAnalyzer', 'CloudSpecialist', or 'HumanAuditor')"
    )
    action_taken: str = Field(description="What was done or decided.")
    reasoning_snapshot: Optional[str] = Field(
        None, description="The rationale or evidence quote for the decision."
    )
    approval_status: Optional[str] = Field(
        None,
        description="Status if this action requires approval (e.g., 'Pending', 'Approved', 'Rejected')",
    )


# --- Phase 1: Planning Artifacts ---
class AuditProcedure(BaseModel):
    control_id: str
    tod_steps: List[str] = Field(
        description="Test of Design steps (e.g., policy review, settings check)."
    )
    toe_steps: List[str] = Field(
        description="Test of Effectiveness steps (e.g., sampling logs over time)."
    )
    substantive_steps: List[str] = Field(
        description="Substantive testing steps for deep-dive transactional evaluation."
    )
    erl_items: List[str] = Field(
        description="Evidence Request List items needed from the auditee."
    )


class ControlMatrixItem(BaseModel):
    control_id: str
    domain: str
    description: str
    procedures: Optional[AuditProcedure] = None


# --- Phase 2: Execution Artifacts ---
class AuditFinding(BaseModel):
    control_id: str
    agent_role: str = Field(
        description="The Swarm Worker role that generated this finding."
    )
    status: Literal["Pass", "Fail", "Exception"] = Field(
        description="Must be exactly: 'Pass', 'Fail', or 'Exception'."
    )
    justification: str = Field(description="Detailed narrative explaining the status.")
    evidence_extracted: List[str] = Field(
        description="Exact quotes or data points from evidence."
    )
    risk_rating: Optional[Literal["High", "Medium", "Low"]] = Field(
        None, description="'High', 'Medium', 'Low', or None for Pass."
    )
    # Per-step results for the Findings Command Center UI
    tod_result: Optional[Literal["Pass", "Fail"]] = Field(
        None, description="'Pass' or 'Fail' for Test of Design."
    )
    toe_result: Optional[Literal["Pass", "Fail", "Exception"]] = Field(
        None, description="'Pass', 'Fail', or 'Exception' for Test of Effectiveness."
    )
    substantive_result: Optional[Literal["Pass", "Fail", "Exception"]] = Field(
        None, description="'Pass', 'Fail', or 'Exception' for Substantive Testing."
    )


# --- Overall Workflow State ---
class AuditState(BaseModel):
    # Phase 1: Planning
    audit_scope_narrative: str = Field(default="")
    risk_themes: List[str] = Field(default_factory=list)
    specialist_roles_required: List[str] = Field(default_factory=list)
    risk_context_document: str = Field(
        default="",
        description="The 1-Pager Risk Context Document generated by the Researcher.",
    )
    control_matrix: List[ControlMatrixItem] = Field(default_factory=list)

    # Skill Modules — populated by Orchestrator, consumed by Researcher & Specialist
    active_skill_ids: List[str] = Field(
        default_factory=list,
        description="IDs of matched skill YAML modules for this audit.",
    )
    active_skill_names: List[str] = Field(
        default_factory=list,
        description="Human-readable names of matched skills for display in the UI.",
    )

    # Phase 2: Execution
    evidence_log: Dict[str, ControlEvidence] = Field(
        default_factory=dict,
        description="Raw mocked JSON payloads or MCP tool outputs loaded for the workers to read.",
    )
    testing_findings: List[AuditFinding] = Field(default_factory=list)
    execution_status: Dict[str, ExecutionStatus] = Field(default_factory=dict)
    # Per-control human feedback, keyed by control_id
    control_feedback: Dict[str, str] = Field(default_factory=dict)
    # Executive summary produced by Concluder agent
    executive_summary: str = Field(default="")

    # Cross-Phase State & Feedback Loop
    # challenger_feedback: set by the Challenger QA agent; routes back to control_mapper
    challenger_feedback: str = Field(
        default="",
        description="QA feedback from the Challenger agent requesting a revision of the control matrix.",
    )
    # revision_feedback: set by the human at Phase 1 review; routes back to researcher
    revision_feedback: str = Field(
        default="",
        description="Instructions from the Human auditor to revise planning artifacts.",
    )
    revision_count: int = Field(
        default=0,
        description="Counter for planning revision loops to prevent infinite cycles.",
    )

    # Global Audit Trail
    audit_trail: List[AuditAction] = Field(
        default_factory=list,
        description="Immutable log of all system and human actions.",
    )

    @staticmethod
    def _coerce_model_value(value: Any) -> Any:
        if hasattr(value, "model_dump"):
            return value.model_dump()
        return value

    @classmethod
    def _coerce_model_list(cls, values: Any) -> Any:
        if not isinstance(values, list):
            return values
        return [cls._coerce_model_value(item) for item in values]

    @field_validator("control_matrix", "testing_findings", "audit_trail", mode="before")
    @classmethod
    def _coerce_legacy_model_lists(cls, values: Any) -> Any:
        return cls._coerce_model_list(values)

    @field_validator("evidence_log", mode="before")
    @classmethod
    def _coerce_legacy_evidence_log(cls, value: Any) -> Any:
        if not isinstance(value, dict):
            return value
        return {key: cls._coerce_model_value(item) for key, item in value.items()}
